[package]
name = "backend"
version = "0.1.0"
authors = ["Jiajie Chen <noc@jiegec.ac.cn>"]
edition = "2018"
default-run = "backend"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.9"
actix-web = "2.0"
actix-web-actors = "2.0"
actix-identity = "0.2"
actix-rt = "1.0"
env_logger = "0.6"
log = "0.4"
ring = "0.16"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
diesel = { version = "1.0.0", features = ["sqlite", "mysql", "r2d2"] }
dotenv = "0.9.0"
paw = "1.0.0"
structopt = { version = "0.3.9", features = ["paw"] }
actix-cors = "0.2.0"
